#spring.application.name=typescript
spring:
  application:
    name: typescript
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/typescript
    username: sa
    password:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

server:
  port: 7172
