#spring.application.name=BoardTest
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/typescript
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #JPA Setting
  jpa:
    #DDL (Data Definition Language) Auto Creation Strategy
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # ???? SQL ??? ???? ???
        show_sql: true
        # ???? SQL ??? ?? ??? ???